/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReactRouteImport } from './routes/api/react'
import { Route as ApiWarmRouteImport } from './routes/api/warm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReactRoute = ApiReactRouteImport.update({
  id: '/api/react',
  path: '/api/react',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarmRoute = ApiWarmRouteImport.update({
  id: '/api/warm',
  path: '/api/warm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/react': typeof ApiReactRoute
  '/api/warm': typeof ApiWarmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/react': typeof ApiReactRoute
  '/api/warm': typeof ApiWarmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/react': typeof ApiReactRoute
  '/api/warm': typeof ApiWarmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/react' | '/api/warm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/react' | '/api/warm'
  id: '__root__' | '/' | '/api/react' | '/api/warm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiReactRoute: typeof ApiReactRoute
  ApiWarmRoute: typeof ApiWarmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/react': {
      id: '/api/react'
      path: '/api/react'
      fullPath: '/api/react'
      preLoaderRoute: typeof ApiReactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warm': {
      id: '/api/warm'
      path: '/api/warm'
      fullPath: '/api/warm'
      preLoaderRoute: typeof ApiWarmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiReactRoute: ApiReactRoute,
  ApiWarmRoute: ApiWarmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
